import { FC } from 'react'
import Head from 'next/head'
import { LayoutProps } from '@/model/LayoutProps'
import { inject, observer } from 'mobx-react'
import InjectNames from '@/store/configuration/storeIdentifier'
import { useAuth } from '@/components/hooks/useAuth'

const AuthenticationLayout: FC<LayoutProps> = ({ children, authenticationStore }) => {
	useAuth('/')

	return (
		<>
			<Head>
				<title>Authentication</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main>
				{children}
			</main>
		</>
	)
}

export default inject(InjectNames.AuthenticationStore)(observer(AuthenticationLayout))