import { FC, ReactNode } from 'react'
import Head from 'next/head'

interface MainLayoutProps {
	children: ReactNode
}

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Easy Base</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main>
				{children}
			</main>
		</>
	)
}

export default MainLayout