import { FC } from 'react'
import Head from 'next/head'
import Header from '@/components/Header'
import SideBar from '@/components/SideBar'
import CreateModal from '@/components/modal/CreateModal'
import DeleteModal from '@/components/modal/DeleteModal'
import UpdateModal from '@/components/modal/UpdateModal'
import { LayoutProps } from '@/model/LayoutProps'
import NotificationMessage from '@/components/NotificationMessage'
import { inject, observer } from 'mobx-react'
import InjectNames from '@/store/configuration/storeIdentifier'
import ContentBar from '@/components/ContentBar'

const MainLayout: FC<LayoutProps> = ({ children, userStore }) => {
	return (
		<>
			<Head>
				<title>Easy Base</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main>
				<Header />
				<div className='main-container'>
					<SideBar />
					<div className='content'>
						<ContentBar />
						{children}
					</div>
				</div>
				<CreateModal />
				<DeleteModal />
				<UpdateModal />
				{userStore?.error && <NotificationMessage message={userStore?.error} />}
			</main>
		</>
	)
}

export default inject(InjectNames.UserStore)(observer(MainLayout))